<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 15/02/2019
 * Time: 11:24 SA
 */
include_once ("Circle.php");
class Cylinder extends Circle
{
    public $height;
    public function Cylinder($radius,$color,$height){
        parent::Circle($radius,$color);
        $this->height = $height;
    }
    public function thetich(){
        echo pow(parent::get_radius(),2)*pi()*$this->height;
    }
    public function toString()
    {
        parent::toString(); // TODO: Change the autogenerated stub
        echo "Chieu cao :".$this->height;


    }
}
?>